### ISSUE TITLE
contact information

### ISSUE THREAD

**Issue by slamonega** [GeoBrodas/nextjs-form-using-google-sheets-api#2]
Hello Georgey, I am writing you from Bahia Blanca, Argentina, I found your repo looking a solution for a problem I have, could you contact me to +5492213144784 via whatsapp or mail to slamonega@gmail.com

Perhaps you can help me and tell me how much is the cost to resolve it. 

regards,
Sebastian

**Comment by GeoBrodas** [comment]
Hey bro it's an open source project and it's for beginner developers to make their first pull request so, yeah it's not paid for 😁

**Comment by slamonega** [comment]
I need an specific form.

- the posibility to upload a photo, Will stored in google drive and a link
in a cell of the sheet, using the drive API.

- Get the geolocalization info.

- Select a couple of categories.

I dont have the skills to do it, could you do it?

Sorry for my basic english.

Sebastián

**Comment by GeoBrodas** [comment]
It's ok bro, the coincidence is, I have already made a repo on it 

Check it out [here](https://github.com/GeoBrodas/multi-step-form-nextjs), it covers all you basic necessities. Only this is geo-location, for that there is a API called [ipStack](https://ipstack.com/).

If you need any help let me know!

**Comment by slamonega** [comment]
WOW, great..

https://no23reason.github.io/react-geolocated/

This Is compatible with the form?

**Comment by GeoBrodas** [comment]
It will be compatible!
